Add-Type -AssemblyName System.Drawing
$root = Split-Path -Parent $PSScriptRoot
$refPath = Join-Path $root 'docs\design-reference.png'
$actualPath = Join-Path $root 'artifacts\browser-qa\desktop-final.png'
$qaPath = Join-Path $root 'artifacts\browser-qa'
$refImage=[Drawing.Image]::FromFile($refPath)
$actualImage=[Drawing.Image]::FromFile($actualPath)
$font=[Drawing.Font]::new('Arial',14)
$full=[Drawing.Bitmap]::new(2974,1090)
$graphics=[Drawing.Graphics]::FromImage($full)
$graphics.Clear([Drawing.Color]::FromArgb(16,18,22))
$graphics.DrawImage($refImage,0,32,1487,1058)
$graphics.DrawImage($actualImage,1487,32,1487,1058)
$graphics.DrawString('SELECTED DESIGN',$font,[Drawing.Brushes]::White,20,6)
$graphics.DrawString('IMPLEMENTATION - FINAL',$font,[Drawing.Brushes]::White,1507,6)
$full.Save((Join-Path $qaPath 'comparison-final.png'),[Drawing.Imaging.ImageFormat]::Png)
$small=[Drawing.Bitmap]::new($full,[Drawing.Size]::new(1487,545))
$small.Save((Join-Path $qaPath 'comparison-final.jpg'),[Drawing.Imaging.ImageFormat]::Jpeg)
$graphics.Dispose()
$small.Dispose()
$full.Dispose()
$detail=[Drawing.Bitmap]::new(1500,285)
$graphics=[Drawing.Graphics]::FromImage($detail)
$graphics.Clear([Drawing.Color]::FromArgb(16,18,22))
$graphics.DrawImage($refImage,[Drawing.Rectangle]::new(0,25,750,260),275,260,750,260,[Drawing.GraphicsUnit]::Pixel)
$graphics.DrawImage($actualImage,[Drawing.Rectangle]::new(750,25,750,260),275,260,750,260,[Drawing.GraphicsUnit]::Pixel)
$graphics.DrawString('DESIGN - EDITOR 1:1',$font,[Drawing.Brushes]::White,12,0)
$graphics.DrawString('IMPLEMENTATION - EDITOR 1:1',$font,[Drawing.Brushes]::White,762,0)
$detail.Save((Join-Path $qaPath 'comparison-editor.jpg'),[Drawing.Imaging.ImageFormat]::Jpeg)
$graphics.Dispose()
$detail.Dispose()
$font.Dispose()
$refImage.Dispose()
$actualImage.Dispose()
